# Generated by Django 5.0 on 2024-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
